framework:
  messenger:
    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
        # Add your transport options here
    routing:
      # Route your messages
      'App\Message\UserCreatedEvent': async